# Generated by Django 6.0 on 2025-12-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
