# Generated by Django 6.0 on 2025-12-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_categoria_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
